/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

/*
 * Preferences
 * Preferences
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.csi.dma.dmacontatti.integration.rest.client.getServices;

import java.util.Objects;
/**
 * Service
 */


public class Service {

  private String uuid = null;


  private String name = null;


  private String channels = null;


  private String tags = null;

  public Service uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * service unique identifier
   * @return uuid
  **/

  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public Service name(String name) {
    this.name = name;
    return this;
  }

   /**
   * service name
   * @return name
  **/

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Service channels(String channels) {
    this.channels = channels;
    return this;
  }

   /**
   * available channels of service
   * @return channels
  **/

  public String getChannels() {
    return channels;
  }

  public void setChannels(String channels) {
    this.channels = channels;
  }

  public Service tags(String tags) {
    this.tags = tags;
    return this;
  }

   /**
   * tags of service
   * @return tags
  **/
  public String getTags() {
    return tags;
  }

  public void setTags(String tags) {
    this.tags = tags;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Service service = (Service) o;
    return Objects.equals(this.uuid, service.uuid) &&
        Objects.equals(this.name, service.name) &&
        Objects.equals(this.channels, service.channels) &&
        Objects.equals(this.tags, service.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, name, channels, tags);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Service {\n");
    
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    channels: ").append(toIndentedString(channels)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
