/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

/*
 * Preferences
 * Preferences
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.csi.dma.dmacontatti.integration.rest.client.getPreferences;

import java.util.Objects;
/**
 * Service
 */


public class Preferences {

  private String uuid = null;


  private String user_id = null;


  private String channels = null;


  private String service_name = null;

  public Preferences uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * service unique identifier
   * @return uuid
  **/

  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public Preferences name(String name) {
    this.user_id = name;
    return this;
  }

   /**
   * service name
   * @return name
  **/

  public String getUser_id() {
    return user_id;
  }

  public void setUser_id(String name) {
    this.user_id = name;
  }

  public Preferences channels(String channels) {
    this.channels = channels;
    return this;
  }

   /**
   * available channels of service
   * @return channels
  **/

  public String getChannels() {
    return channels;
  }

  public void setChannels(String channels) {
    this.channels = channels;
  }

  public Preferences service_name(String service_name) {
    this.service_name = service_name;
    return this;
  }

   /**
   * tags of service
   * @return tags
  **/
  public String getService_name() {
    return service_name;
  }

  public void setService_name(String service_name) {
    this.service_name = service_name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Preferences service = (Preferences) o;
    return Objects.equals(this.uuid, service.uuid) &&
        Objects.equals(this.user_id, service.user_id) &&
        Objects.equals(this.channels, service.channels) &&
        Objects.equals(this.service_name, service.service_name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, user_id, channels, service_name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Service {\n");
    
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    user_id: ").append(toIndentedString(user_id)).append("\n");
    sb.append("    channels: ").append(toIndentedString(channels)).append("\n");
    sb.append("    service_name: ").append(toIndentedString(service_name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
