/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.dma.dmafarma;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-11-29T09:39:58.432+01:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://dmafarma.dma.csi.it/", name = "FarmacieService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FarmacieService {

    @WebMethod
    @WebResult(name = "getDelegantiFarmaciaResponse", targetNamespace = "http://dmafarma.dma.csi.it/", partName = "getDelegantiFarmaciaResponse")
    public GetDelegantiFarmaciaResponse getDelegantiFarmacia(
        @WebParam(partName = "getDelegantiFarmacia", name = "getDelegantiFarmacia", targetNamespace = "http://dmafarma.dma.csi.it/")
        GetDelegantiFarmaciaRequest getDelegantiFarmacia
    );

    @WebMethod
    @WebResult(name = "elencoRicetteFarmaciaResponse", targetNamespace = "http://dmafarma.dma.csi.it/", partName = "elencoRicetteFarmaciaResponse")
    public ElencoRicetteFarmaciaResponse elencoRicetteFarmacia(
        @WebParam(partName = "elencoRicetteFarmacia", name = "elencoRicetteFarmacia", targetNamespace = "http://dmafarma.dma.csi.it/")
        ElencoRicetteFarmaciaRequest elencoRicetteFarmacia
    );
}
