/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.dma.farmab.interfacews.IF;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import it.csi.dma.farmab.interfacews.msg.getelencofarmacieabituali.GetElencoFarmacieAbitualiRequest;
import it.csi.dma.farmab.interfacews.msg.getelencofarmacieabituali.GetElencoFarmacieAbitualiResponse;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-10-17T18:26:38.204+02:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://getelencofarmacieabituali.msg.interfacews.farmab.dma.csi.it/", name = "GetElencoFarmacieAbitualiService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetElencoFarmacieAbitualiService {

    @WebMethod
    @WebResult(name = "getElencoFarmacieAbitualiResponse", targetNamespace = "http://getelencofarmacieabituali.msg.interfacews.farmab.dma.csi.it/", partName = "getElencoFarmacieAbitualiResponse")
    public GetElencoFarmacieAbitualiResponse getElencoFarmacieAbituali(
    		 @WebParam(partName = "getElencoFarmacieAbituali", name = "getElencoFarmacieAbituali", targetNamespace = "http://getelencofarmacieabituali.msg.interfacews.farmab.dma.csi.it/")
    		 GetElencoFarmacieAbitualiRequest getElencoFarmacieAbituali
    );
}
