/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.dma.farmab.interfacews.IF;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import it.csi.dma.farmab.interfacews.msg.getgeneraotpdevice.GetGeneraOtpDeviceRequest;
import it.csi.dma.farmab.interfacews.msg.getgeneraotpdevice.GetGeneraOtpDeviceResponse;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-10-14T17:01:50.156+02:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://getgeneraotpdevice.msg.interfacews.farmab.dma.csi.it/", name = "GetGeneraOtpDeviceService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetGeneraOtpDeviceService {

	
	@WebMethod
    @WebResult(name = "getGeneraOtpDeviceResponse", targetNamespace = "http://getgeneraotpdevice.msg.interfacews.farmab.dma.csi.it/", partName = "getGeneraOtpDeviceResponse")
    public GetGeneraOtpDeviceResponse getGeneraOtpDevice(
        @WebParam(partName = "getGeneraOtpDevice", name = "getGeneraOtpDevice", targetNamespace = "http://getgeneraotpdevice.msg.interfacews.farmab.dma.csi.it/")
        GetGeneraOtpDeviceRequest getGeneraOtpDevice
    );
	
}
