/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.dma.farmab.interfacews.IF;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import it.csi.dma.farmab.interfacews.msg.setdisassociadevice.SetDisassociaDeviceRequest;
import it.csi.dma.farmab.interfacews.msg.setdisassociadevice.SetDisassociaDeviceResponse;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-10-12T10:39:24.834+02:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://setdisassociadevice.msg.interfacews.farmab.dma.csi.it/", name = "SetDisassociaDeviceService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SetDisassociaDeviceService {

    @WebMethod
    @WebResult(name = "setDisassociaDeviceResponse", targetNamespace = "http://setdisassociadevice.msg.interfacews.farmab.dma.csi.it/", partName = "setDisassociaDeviceResponse")
    public SetDisassociaDeviceResponse setDisassociaDevice(
        @WebParam(partName = "setDisassociaDevice", name = "setDisassociaDevice", targetNamespace = "http://setdisassociadevice.msg.interfacews.farmab.dma.csi.it/")
        SetDisassociaDeviceRequest setDisassociaDevice
    );
}
