/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.ricercadocumentiini.dmacc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2023-01-23T14:06:48.948+01:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://dmacc.csi.it/", name = "RicercaDocumentiINIService")
@XmlSeeAlso({it.csi.ricercadocumentiini.dma.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RicercaDocumentiINIService {

    @WebMethod
    @WebResult(name = "ricercaDocumentiResponse", targetNamespace = "http://dmacc.csi.it/", partName = "ricercaDocumentiResponse")
    public RicercaDocumentiResponse ricercaDocumenti(
        @WebParam(partName = "ricercaDocumenti", name = "ricercaDocumenti", targetNamespace = "http://dmacc.csi.it/")
        RicercaDocumentiRequeste ricercaDocumenti
    );
}
